plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs32.github.io 
baseurl: "/s20"

course: "CS32"
qtr: "S20"
quarter: "Spring 2020"
piazza_url: https://piazza.com/ucsb/spring2020/cs32/home
gauchospace_course_page:
gradescope_class_url: https://www.gradescope.com/courses/105132

ta_list: "Aiwen, Yaoyi"
ta_list_full: "Aiwen Xu, Yaoyi Bai"
mentors_list: "April Sanchez, Adam Snaider, Alan Roddick, Brandon Nadell, Jennice Xu, Jim Wan"
discussion_section_times: "3pm, 4pm, 5pm, 6pm"

github_url: https://github.com/ucsb-cs32/s20
mentor_url:

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048

submit_cs_course:

start_week: 0
start_date: 2020-03-29 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true
sections: "TO DO"

cal_dates: >
  [
  {"label":"First day of Spring Quarter", "date":"2020-03-30" },
  {"label":"Univ Holiday: Memorial Day", "date":"2020-05-25" },
  {"label":"Last day of instruction", "date":"2020-06-05" },
  {"label":"Finals Begin", "date":"2020-06-06" },
  {"label":"Finals End", "date":"2020-06-12" },
  {"label":"Last day to drop (11pm)", "date":"2020-04-24" }
  ]


kramdown:
   parse_block_html: true
   default_lang: python

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
